import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-0 my-6">
        <h1 className="text-2xl font-bold text-green-300 underline ">
          Tailwind css
        </h1>
      </main>
    </div>
  );
}
